#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    foreground = 'p:blue'
    style = 'plain'
    template = '{{ if .SSHSession }}{{ .UserName }}@{{ .HostName }}{{ end }} '
    type = 'session'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:pink'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'
      home_icon = '~'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:sky'
    background = 'transparent'
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} *{{ end }}{{ if gt .Behind 0 }}{{ end }} {{ if gt .Ahead 0 }}{{ end }}'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true


[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = "java"
    style = "plain"
    foreground = "p:peach"
    background = "transparent"
    template = " {{ if .Error }}{{ .Error }}{{ else }}{{ .Major }}{{ end }}"

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "p:peach"
    background = "transparent"
    template = ' {{ if .Error }} {{ .Error }}{{ else }}{{ if and .Venv (ne .Venv "base") }} {{ .Venv }} {{ .Full }}{{ end }}{{ end }}'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'p:surface1'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'


  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:lavender{{end}}",
    ]
    background = 'transparent'
    template = ' '


[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:lavender{{end}}",
  ]
  background = 'transparent'
  template = ' '

[palette]
  os = "#ACB0BE"
  closer = "#ACB0BE"
  pink = "#F5C2E7"
  lavender = "#B4BEFE"
  blue = "#89B4FA"
  surface1 = "#45475A"
  red = "#F38BA8"
  base = "#1E1E2E"
  crust = "#11111B"
  yellow = "#F9E2AF"
  peach = "#FAB387"
  sky = "#89DCEB"
  sapphire = "#74C7EC"
  green = "#A6E3A1"
  mauve = "#CBA6F7"

[secondary_prompt]
  foreground = "p:mauve"
  background = "transparent"
  template = ' '
